version: '3'

services:
  web:
    image: rabbitmq:3-management
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
    ports:
      - "15672:15672"
    networks:
      - webnet
networks:
  webnet: